### ISSUE TITLE
[11.0] crm_phonecall error on "Schedule Another Call"

### ISSUE THREAD

**Issue by anandkansagra** [OCA/crm#248] opened 2018-12-01 09:48 UTC
There seems an error while `Schedule Another Call` from `CRM -> Phone Calls -> Logged Calls`
![1](https://user-images.githubusercontent.com/45279628/49326701-3cd2d500-f57c-11e8-8511-b16e9cfb877f.gif)

**Comment by pedrobaeza** [comment] 2018-12-01 09:56
Duplicate of #236

**Comment by pedrobaeza** [comment] 2018-12-01 13:15
It seems not duplicate it at all, so I reopen.

**Comment by anandkansagra** [comment] 2018-12-01 14:22
> It seems not duplicate it at all, so I reopen.

@pedrobaeza ,
I have fixed this thing in code migration in `12.0` 
PR [Reference](https://github.com/OCA/crm/pull/247)

**Closed as completed** 2018-12-02 20:53 UTC
