### ISSUE TITLE
[8.0] crm_claim_type fails at update

### ISSUE THREAD

**Issue by aristobulo-eezee** [OCA/crm#69] opened 2015-11-24 13:59 UTC
Commit: 542109b02551d82e6f4ab29ab96cae34139e2fbe

When I try to update all modules it breaks

```
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (31, 1, 1, 2015-11-24 13:45:36.624852, 2015-11-24 13:45:36.624852, null, 1, null, null, f, null, t, null).
" while parsing /opt/local/odoo/addons-LPW/addons-community/oca/crm/crm_claim_type/data/crm_claim_stage.xml:4, near
<record id="crm_claim.stage_claim1" model="crm.claim.stage">
            <field name="claim_common">1</field>
        </record>
```

**Comment by osvalr** [comment] 2015-11-24 16:06
Hi @aristobulo-eezee,

Can you add steps to reproduce the error? I've tested out and cannot reproduce the error,
Can you add to the issue description a more detailed information about it?

By the way, I don't see the commit at OCA/crm

Thanks in advance

**Comment by pedrobaeza** [comment] 2016-03-02 07:54
As there's no answer since November, I close this one.

**Closed as completed by pedrobaeza** 2016-03-02 07:54 UTC
